### ISSUE TITLE
Indium Crashing on latest version when placing brass casing

### ISSUE THREAD

**Issue by DirefulBelt6803** [leon-o/iris-flw-compat#109]
- Complementary Shaders - Reimagined by EminGT
r5.1.1

- Create Fabric by tropheusj
0.5.1-f-build.1335+mc1.20.1

- Fabric API by modmuss50
0.91.0+1.20.1

- Indium by comp500
1.0.23+mc1.20.1

- Iris & Oculus Flywheel Compat by leon-o
1.20.1-0.2.1

- Iris Flywheel Compat
0.2.4

- Iris Shaders by coderbot
1.6.5+1.20.1

- Sodium by jellysquid3
mc1.20.1-0.5.0

Time: 2024-03-27 00:27:46
Description: Tessellating block in world - Indium Renderer

java.lang.IllegalAccessError: 'boolean link.infra.indium.renderer.render.TerrainRenderContext.hasTransform()'
	at net.fabricmc.fabric.impl.renderer.VanillaModelEncoder.emitBlockQuads(VanillaModelEncoder.java:54)
	at net.fabricmc.fabric.api.renderer.v1.model.FabricBakedModel.emitBlockQuads(FabricBakedModel.java:97)
	at net.fabricmc.fabric.api.renderer.v1.model.ForwardingBakedModel.emitBlockQuads(ForwardingBakedModel.java:51)
	at com.simibubi.create.foundation.block.connected.CTModel.emitBlockQuads(CTModel.java:86)
	at link.infra.indium.renderer.render.TerrainRenderContext.tessellateBlock(TerrainRenderContext.java:131)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.redirect$bdk000$indium$onRenderBlock(ChunkBuilderMeshingTask.java:1043)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:104)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.tasks.ChunkBuilderMeshingTask.execute(ChunkBuilderMeshingTask.java:40)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkJobTyped.execute(ChunkJobTyped.java:41)
	at me.jellysquid.mods.sodium.client.render.chunk.compile.executor.ChunkBuilder$WorkerRunnable.run(ChunkBuilder.java:206)
	at java.base/java.lang.Thread.run(Unknown Source)
	
[crash-2024-03-27_00.27.46-client.txt](https://github.com/leon-o/iris-flw-compat/files/14770221/crash-2024-03-27_00.27.46-client.txt)

**Comment by DirefulBelt6803** [comment]
Other blocks crash indium as well, though I don't want to make a list of all of them if I can help it

**Comment by Poopooracoocoo** [comment]
Even at the time of your post, your versions of Indium, Sodium, etc were out of date...

**Comment by DirefulBelt6803** [comment]
I don't even remember what I was doing at that time, closing
