### ISSUE TITLE
---- Minecraft Crash Report ----

### ISSUE THREAD

**Issue by esxwilliamsx33** [leon-o/iris-flw-compat#182]
---- Minecraft Crash Report ----
// This doesn't make any sense!

Time: 2024-11-24 17:01:07
Description: Unexpected error

java.lang.ClassCastException: class com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher$1 cannot be cast to class net.minecraft.class_638 (com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher$1 and net.minecraft.class_638 are in unnamed module of loader 'knot' @56620197)
	at knot//ca.spottedleaf.starlight.common.light.StarLightEngine.causeSnowLightUpdate(StarLightEngine.java:1666)
	at knot//ca.spottedleaf.starlight.common.light.StarLightEngine.handler$ejd000$physicsmod$setLightLevel(StarLightEngine.java:1655)
	at knot//ca.spottedleaf.starlight.common.light.StarLightEngine.setLightLevel(StarLightEngine.java)
	at knot//ca.spottedleaf.starlight.common.light.BlockStarLightEngine.checkBlock(BlockStarLightEngine.java:100)
	at knot//ca.spottedleaf.starlight.common.light.BlockStarLightEngine.propagateBlockChanges(BlockStarLightEngine.java:200)
	at knot//ca.spottedleaf.starlight.common.light.StarLightEngine.blocksChangedInChunk(StarLightEngine.java:428)
	at knot//ca.spottedleaf.starlight.common.light.StarLightInterface.propagateChanges(StarLightInterface.java:552)
	at knot//net.minecraft.class_3568.method_15516(class_3568.java:1599)
	at knot//com.jozufozu.flywheel.core.virtual.VirtualRenderWorld.runLightEngine(VirtualRenderWorld.java:136)
	at knot//com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.setupRenderWorld(ContraptionRenderDispatcher.java:130)
	at knot//com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:84)
	at knot//com.simibubi.create.content.contraptions.render.FlwContraptionManager.create(FlwContraptionManager.java:22)
	at knot//com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.getRenderInfo(ContraptionRenderingWorld.java:95)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.accept(ForEachOps.java:184)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.stream.ReferencePipeline$2$1.accept(ReferencePipeline.java:179)
	at java.base/java.util.stream.ReferencePipeline$3$1.accept(ReferencePipeline.java:197)
	at java.base/java.util.HashMap$ValueSpliterator.forEachRemaining(HashMap.java:1787)
	at java.base/java.util.stream.AbstractPipeline.copyInto(AbstractPipeline.java:509)
	at java.base/java.util.stream.AbstractPipeline.wrapAndCopyInto(AbstractPipeline.java:499)
	at java.base/java.util.stream.ForEachOps$ForEachOp.evaluateSequential(ForEachOps.java:151)
	at java.base/java.util.stream.ForEachOps$ForEachOp$OfRef.evaluateSequential(ForEachOps.java:174)
	at java.base/java.util.stream.AbstractPipeline.evaluate(AbstractPipeline.java:234)
	at java.base/java.util.stream.ReferencePipeline.forEach(ReferencePipeline.java:596)
	at knot//com.simibubi.create.content.contraptions.render.ContraptionRenderingWorld.tick(ContraptionRenderingWorld.java:68)
	at knot//com.simibubi.create.content.contraptions.render.FlwContraptionManager.tick(FlwContraptionManager.java:30)
	at knot//com.simibubi.create.content.contraptions.render.ContraptionRenderDispatcher.tick(ContraptionRenderDispatcher.java:65)
	at knot//com.simibubi.create.foundation.events.ClientEvents.onTick(ClientEvents.java:191)
	at knot//net.fabricmc.fabric.api.client.event.lifecycle.v1.ClientTickEvents.lambda$static$2(ClientTickEvents.java:43)
	at knot//net.minecraft.class_310.handler$bpg000$fabric-lifecycle-events-v1$onEndTick(class_310.java:11022)
	at knot//net.minecraft.class_310.method_1574(class_310.java:1957)
	at knot//net.minecraft.class_310.method_1523(class_310.java:1181)
	at knot//net.minecraft.class_310.method_1514(class_310.java:802)
	at knot//net.minecraft.client.main.Main.main(Main.java:250)
	at net.fabricmc.loader.impl.game.minecraft.MinecraftGameProvider.launch(MinecraftGameProvider.java:480)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:74)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)
	at java.base/jdk.internal.reflect.DirectMethodHandleAccessor.invoke(DirectMethodHandleAccessor.java:103)
	at java.base/java.lang.reflect.Method.invoke(Method.java:580)
	at oolloo.jlw.Wrapper.invokeMain(Wrapper.java:110)
	at oolloo.jlw.Wrapper.main(Wrapper.java:103)

**Comment by Poopooracoocoo** [comment]
irisflw is mentioned at all here. 

You've got Starlight which isn't compatible with Create. Starlight isn't necessary on 1.20 and above.

And for future reference, share the whole crash report, not just a snippet.

**Comment by leon-o** [comment]
Duplicate of #236. Closing in favor of the original issue.
