### ISSUE TITLE
Mods requires Flywheel when its already installed

### ISSUE THREAD

**Issue by doubleaxes** [leon-o/iris-flw-compat#41]
error:
Incompatible mod set!
net.fabricmc.loader.impl.FormattedException: Mod resolution encountered an incompatible mod set!
A potential solution has been determined:
	 - Install flywheel, any version.
Unmet dependency listing:
	 - Mod 'Iris Flywheel Compat' (irisflw) 0.1.9-BETA requires any version of flywheel, which is missing!
	at net.fabricmc.loader.impl.FabricLoaderImpl.load(FabricLoaderImpl.java:190)
	at net.fabricmc.loader.impl.launch.knot.Knot.init(Knot.java:148)
	at net.fabricmc.loader.impl.launch.knot.Knot.launch(Knot.java:68)
	at net.fabricmc.loader.impl.launch.knot.KnotClient.main(KnotClient.java:23)

I have downloaded flywheel from here https://www.curseforge.com/minecraft/mc-mods/flywheel/files (I think its the right file? Im not sure) but it still gives this error

**Comment by Shadow091995** [comment]
That is Flywheel for forge. Flywheel is bundled into Create on Fabric.

**Comment by leon-o** [comment]
If you use fabric, just install create mod and you're done!
