### ISSUE TITLE
Crash with create 0.5.1c+

### ISSUE THREAD

**Issue by n-507** [leon-o/iris-flw-compat#55]
Mixin crash occur with:
| mod | version |
| --- | --- |
| `minecraft` | 1.19.2 |
| `forge` | 1.19.2 - 43.2.14 |
| `create` | 0.5.1c+ |
| `irisfw` | 0.2.0 | 
| `oculus` | 1.6.4 |

Other minecraft version untested but a crash can be expected.
The crash is caused due to failed mixin. The original method have moved due to `flywheel` upgrade in `create` 0.5.1c.

The new method is refactored to [`ModelUtil#getBufferedData(Bufferable)`](https://github.com/Jozufozu/Flywheel/commit/af3d9f74252ca5388c78d61ba7102636940ac75d#diff-b5481b97cbb9e2d6ff5e91f37aab3ac243e2d44496633c18afc9a18b002900caR74). This caused existing mixin to fail.

Related stack trace:
```
Caused by: org.spongepowered.asm.mixin.throwables.MixinApplyError: Mixin [irisflw.mixins.flw.json:MixinModelUtil] from phase [DEFAULT] in config [irisflw.mixins.flw.json] FAILED during APPLY
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinError(MixinProcessor.java:636) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.handleMixinApplyError(MixinProcessor.java:588) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:379) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 76 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InvalidInjectionException: Critical injection failure: Callback group @Group(name=getBufferBuilderHead, min=1, max=2) in irisflw.mixins.flw.json:MixinModelUtil failed injection check: expected 1 invocation(s) but 0 succeeded [ -> PostApply Phase -> irisflw.mixins.flw.json:MixinModelUtil]
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1262) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:344) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 76 more
Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionValidationException: expected 1 invocation(s) but 0 succeeded
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo.validate(InjectorGroupInfo.java:268) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.injection.struct.InjectorGroupInfo$Map.validateAll(InjectorGroupInfo.java:126) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinTargetContext.postApply(MixinTargetContext.java:1255) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinApplicatorStandard.apply(MixinApplicatorStandard.java:344) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.apply(TargetClassContext.java:383) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.TargetClassContext.applyMixins(TargetClassContext.java:365) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	at org.spongepowered.asm.mixin.transformer.MixinProcessor.applyMixins(MixinProcessor.java:363) ~[mixin-0.8.5.jar:0.8.5+Jenkins-b310.git-155314e6e91465dad727e621a569906a410cd6f4] {}
	... 76 more
```

**Comment by leon-o** [comment]
Thanks!
